import { useEffect, useMemo, useRef, useState } from 'react'
import './App.css'

const COLORS = ['#3578f6', '#5cc9a5', '#9b73ed', '#ffad4a', '#f36d8d']
const ICONS = ['◈', '▣', '◆', '⌂', '★']
const now = new Date().toISOString()
const seed = [
  ['angielski', null, 'main', 'Nauka języka angielskiego', 'Małe kroki każdego dnia.', '2026-08-30', 0],
  ['slowka', 'angielski', 'subtask', 'Słówka', 'Codziennie ucz się nowych słówek i utrwalaj wcześniejsze poznane.', '2026-08-20', 0],
  ['hello', 'slowka', 'detail', 'Hello', '', '', 0, true],
  ['how', 'slowka', 'detail', 'How are you?', '', '', 0],
  ['thanks', 'slowka', 'detail', 'Thank you', '', '', 0],
  ['gramatyka', 'angielski', 'subtask', 'Gramatyka', 'Present Simple', '2026-08-25', 1],
  ['praca', null, 'main', 'Projekt do pracy', 'Materiały i prezentacja', '2026-09-10', 1],
  ['trening', null, 'main', 'Trening', 'Plan treningowy', '', 2],
  ['dom', null, 'main', 'Domowe obowiązki', '', '', 3],
].map(([id,parentId,level,title,description,dueDate,color,completed=false])=>({id,parentId,level,title,description,dueDate,color,completed,archived:completed,completedAt:completed?now:null,deleted:false,images:[],createdAt:now}))
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`
const fmt=(d,time=false)=>d?new Intl.DateTimeFormat('pl-PL',time?{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d)):''

export default function App(){
 const [tasks,setTasks]=useState(()=>{try{return JSON.parse(localStorage.getItem('planner-tasks'))||seed}catch{return seed}})
 const [view,setView]=useState({name:'home'}),[toast,setToast]=useState(''),[filter,setFilter]=useState('Wszystkie')
 const timer=useRef()
 useEffect(()=>localStorage.setItem('planner-tasks',JSON.stringify(tasks)),[tasks])
 const parent=id=>tasks.find(t=>t.id===id), children=id=>tasks.filter(t=>t.parentId===id&&!t.deleted), active=id=>children(id).filter(t=>!t.archived)
 const nav=v=>{setView(v);scrollTo(0,0)}
 const flash=m=>{setToast(m);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),2800)}
 const toggle=t=>{const done=!t.completed,n=new Date().toISOString();setTasks(a=>a.map(x=>x.id===t.id?{...x,completed:done,archived:done,completedAt:done?n:null,archivedAt:done?n:null}:x));flash(done?'Gotowe! Przeniesiono do archiwum.':'Zadanie przywrócono.')}
 const trash=t=>{const ids=new Set([t.id]);let change=true;while(change){change=false;tasks.forEach(x=>{if(ids.has(x.parentId)&&!ids.has(x.id)){ids.add(x.id);change=true}})};setTasks(a=>a.map(x=>ids.has(x.id)?{...x,deleted:true,deletedAt:new Date().toISOString()}:x));flash('Przeniesiono do kosza.');nav({name:'home'})}
 const save=d=>{const n=new Date().toISOString();if(d.id)setTasks(a=>a.map(x=>x.id===d.id?{...x,...d,updatedAt:n}:x));else setTasks(a=>[...a,{...d,id:uid(),createdAt:n,completed:false,archived:false,deleted:false,images:d.images||[],color:d.color??a.length%5}]);flash(d.id?'Zmiany zapisane.':'Dodano nowe zadanie.');if(d.parentId)nav({name:'task',id:d.parentId});else nav({name:'home'})}
 const path=t=>{const names=[];let x=t;while(x?.parentId){x=parent(x.parentId);if(x)names.unshift(x.title)}return names.join(' › ')}
 const cur=parent(view.id)
 let page
 if(view.name==='form')page=<TaskForm task={cur} parentTask={parent(view.parentId)} onCancel={()=>view.parentId?nav({name:'task',id:view.parentId}):nav({name:'home'})} onSave={save} onTrash={trash}/>
 else if(view.name==='archive')page=<Archive tasks={tasks} filter={filter} setFilter={setFilter} path={path} onRestore={toggle} onTrash={trash}/>
 else if(view.name==='trash')page=<Trash tasks={tasks} setTasks={setTasks} flash={flash}/>
 else if(view.name==='task'&&cur)page=<TaskView task={cur} items={active(cur.id)} getChildren={children} onBack={()=>cur.parentId?nav({name:'task',id:cur.parentId}):nav({name:'home'})} onOpen={id=>nav({name:'task',id})} onAdd={()=>nav({name:'form',parentId:cur.id})} onEdit={id=>nav({name:'form',id})} onToggle={toggle}/>
 else page=<Home tasks={tasks.filter(t=>!t.parentId&&!t.archived&&!t.deleted)} getChildren={children} onOpen={id=>nav({name:'task',id})} onAdd={()=>nav({name:'form'})} onEdit={id=>nav({name:'form',id})}/>
 return <main className="phone-app">{page}{view.name!=='form'&&<BottomNav active={view.name} go={nav}/>} {toast&&<div className="toast"><span>✓</span>{toast}</div>}</main>
}

function Header({title='Moje zadania',back,onBack,action}){return <header className="topbar"><button className="icon-btn" onClick={onBack}>{back?'‹':'☰'}</button><strong>{title}</strong>{action?<button className="add-round" onClick={action} aria-label="Dodaj zadanie"/>:<span/>}</header>}
function Home({tasks,getChildren,onOpen,onAdd,onEdit}){const total=tasks.reduce((n,t)=>n+getChildren(t.id).length,0);return <><Header action={onAdd}/><section className="content"><div className="welcome"><div><span>Dzień dobry 👋</span><h1>Twój plan na dziś</h1><p>{tasks.length} obszarów · {total} zadań</p></div><div className="date-badge"><b>{new Date().getDate()}</b><span>{new Intl.DateTimeFormat('pl-PL',{month:'short'}).format(new Date()).replace('.','')}</span></div></div><button className="primary" onClick={onAdd}>＋ Dodaj zadanie główne</button><Title text="Moje zadania" n={tasks.length}/><div className="task-list">{tasks.map((t,i)=><TaskRow key={t.id} task={t} kids={getChildren(t.id)} color={i} onOpen={()=>onOpen(t.id)} onEdit={()=>onEdit(t.id)}/>)}</div>{!tasks.length&&<Empty text="Tu pojawią się Twoje zadania." action={onAdd}/>}</section></>}
function TaskRow({task,kids=[],color=0,onOpen,onEdit,onToggle}){const done=kids.filter(x=>x.completed).length;return <article className="task-row" onClick={onOpen}>{onToggle?<button className={`check ${task.completed?'checked':''}`} onClick={e=>{e.stopPropagation();onToggle()}}>{task.completed?'✓':''}</button>:<div className="task-symbol" style={{'--tone':COLORS[task.color??color%5]}}>{ICONS[task.color??color%5]}</div>}<div className="task-copy"><h3>{task.title}</h3><p>{task.dueDate?`Do ${fmt(task.dueDate)}`:kids.length?`${done} z ${kids.length} wykonane`:'Bez terminu'}</p>{kids.length>0&&<div className="progress"><i style={{width:`${done/kids.length*100}%`}}/></div>}</div><button className="more" onClick={e=>{e.stopPropagation();onEdit()}}>•••</button><span className="chev">›</span></article>}
function TaskView({task,items,getChildren,onBack,onOpen,onAdd,onEdit,onToggle}){const details=task.level==='subtask';return <><Header title={task.title} back onBack={onBack} action={onAdd}/><section className="content"><div className="task-hero"><div className="task-symbol large" style={{'--tone':COLORS[task.color||0]}}>{ICONS[task.color||0]}</div><div><p>{details?'Podzadanie':'Zadanie główne'}</p><h1>{task.title}</h1></div><button className="edit-pill" onClick={()=>onEdit(task.id)}>Edytuj</button></div>{(task.description||task.dueDate)&&<div className="info-card">{task.dueDate&&<div><span>Termin</span><b>▣ {fmt(task.dueDate)}</b></div>}{task.description&&<div><span>Opis</span><p>{task.description}</p></div>}</div>}{task.images?.length>0&&<div className="photos">{task.images.map((s,i)=><img key={i} src={s}/>)}</div>}<button className="primary" onClick={onAdd}>＋ {details?'Dodaj szczegółowy krok':'Dodaj podzadanie'}</button><Title text={details?'Kroki do wykonania':'Podzadania'} n={items.length}/><div className="task-list">{items.map(t=><TaskRow key={t.id} task={t} kids={getChildren(t.id)} onOpen={()=>t.level==='detail'?onEdit(t.id):onOpen(t.id)} onEdit={()=>onEdit(t.id)} onToggle={()=>onToggle(t)}/>)}</div>{!items.length&&<Empty text="Brak elementów. Dodaj pierwszy krok." action={onAdd}/>}</section></>}
function TaskForm({task,parentTask,onSave,onCancel,onTrash}){const [d,setD]=useState(()=>task?{...task}:{parentId:parentTask?.id||null,level:parentTask?(parentTask.level==='main'?'subtask':'detail'):'main',title:'',description:'',dueDate:'',images:[]});const ref=useRef();const files=e=>Array.from(e.target.files).slice(0,3).forEach(f=>{const r=new FileReader();r.onload=()=>setD(x=>({...x,images:[...(x.images||[]),r.result].slice(0,3)}));r.readAsDataURL(f)});return <><Header title={task?'Edytuj zadanie':'Nowe zadanie'} back onBack={onCancel}/><form className="content form" onSubmit={e=>{e.preventDefault();if(d.title.trim())onSave({...d,title:d.title.trim()})}}><div className="form-intro"><span>{task?'✎':'＋'}</span><div><h1>{task?'Zmień szczegóły':'Co planujesz?'}</h1><p>{parentTask?`W: ${parentTask.title}`:'Zacznij od prostego, konkretnego celu.'}</p></div></div><label>Nazwa zadania<input autoFocus required maxLength="80" value={d.title} onChange={e=>setD({...d,title:e.target.value})} placeholder="Np. Nauka języka angielskiego"/></label><label>Opis <em>opcjonalnie</em><textarea rows="4" value={d.description} onChange={e=>setD({...d,description:e.target.value})} placeholder="Dodaj kilka szczegółów..."/></label><label>Termin <em>opcjonalnie</em><input type="date" value={d.dueDate} onChange={e=>setD({...d,dueDate:e.target.value})}/></label><label>Zdjęcia i załączniki <em>do 3</em></label><div className="photo-grid">{d.images?.map((s,i)=><div className="photo" key={i}><img src={s}/><button type="button" onClick={()=>setD({...d,images:d.images.filter((_,n)=>n!==i)})}>×</button></div>)}{(d.images?.length||0)<3&&<button type="button" className="photo-add" onClick={()=>ref.current.click()}>▧<span>Dodaj zdjęcie</span></button>}</div><input ref={ref} hidden type="file" accept="image/*" capture="environment" multiple onChange={files}/><button className="primary save">Zapisz zadanie</button>{task&&<button type="button" className="danger" onClick={()=>confirm(`Przenieść „${task.title}” do kosza?`)&&onTrash(task)}>♲ Przenieś do kosza</button>}</form></>}
function Archive({tasks,filter,setFilter,path,onRestore,onTrash}){const list=useMemo(()=>tasks.filter(t=>t.archived&&!t.deleted).filter(t=>filter==='Dzisiaj'?new Date(t.completedAt).toDateString()===new Date().toDateString():filter==='7 dni'?Date.now()-new Date(t.completedAt)<604800000:true).sort((a,b)=>new Date(b.completedAt)-new Date(a.completedAt)),[tasks,filter]);return <><Header title="Archiwum"/><section className="content"><Heading small="Twoje postępy" text="Wykonane zadania"/><div className="filters">{['Wszystkie','Dzisiaj','7 dni'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="archive-list">{list.map(t=><ArchiveRow key={t.id} task={t} subtitle={path(t)||'Zadanie główne'} onRestore={()=>onRestore(t)} onRemove={()=>onTrash(t)}/>)}</div>{!list.length&&<Empty text="Brak wykonanych zadań w tym okresie."/ >}</section></>}
function ArchiveRow({task,subtitle,onRestore,onRemove,trash}){return <article className="archive-row"><span className={trash?'trash-icon':''}>{trash?'♲':'✓'}</span><div><h3>{task.title}</h3>{subtitle&&<p>{subtitle}</p>}<small>{trash?'Usunięto':'Wykonano'} {fmt(trash?task.deletedAt:task.completedAt,true)}</small></div><button onClick={onRestore}>Przywróć</button><button className="mini-trash" onClick={onRemove}>{trash?'×':'♲'}</button></article>}
function Trash({tasks,setTasks,flash}){const list=tasks.filter(t=>t.deleted);return <><Header title="Kosz"/><section className="content"><Heading small="Bezpieczne usuwanie" text="Usunięte zadania"/><div className="archive-list">{list.map(t=><ArchiveRow trash key={t.id} task={t} onRestore={()=>{setTasks(a=>a.map(x=>x.id===t.id?{...x,deleted:false}:x));flash('Zadanie przywrócono.')}} onRemove={()=>confirm('Usunąć na zawsze?')&&setTasks(a=>a.filter(x=>x.id!==t.id))}/>)}</div>{!list.length&&<Empty text="Kosz jest pusty."/ >}</section></>}
function Title({text,n}){return <div className="section-title"><h2>{text}</h2><span>{n}</span></div>}function Heading({small,text}){return <div className="page-heading"><p>{small}</p><h1>{text}</h1></div>}function Empty({text,action}){return <div className="empty"><div>✓</div><h3>Wszystko uporządkowane</h3><p>{text}</p>{action&&<button onClick={action}>Dodaj zadanie</button>}</div>}
function BottomNav({active,go}){return <nav className="bottom-nav"><button className={['home','task'].includes(active)?'active':''} onClick={()=>go({name:'home'})}><b>⌂</b><span>Plan</span></button><button className="center-add" onClick={()=>go({name:'form'})}>+</button><button className={active==='archive'?'active':''} onClick={()=>go({name:'archive'})}><b>▣</b><span>Archiwum</span></button><button className={active==='trash'?'active':''} onClick={()=>go({name:'trash'})}><b>♲</b><span>Kosz</span></button></nav>}
