import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import './App.css'
import ProjectPlanner from './ProjectPlanner'
import { getFocus } from './plan'

const COLORS = ['#3578f6', '#5cc9a5', '#9b73ed', '#ffad4a', '#f36d8d']
const ICONS = ['◈', '▣', '◆', '⌂', '★']
const now = new Date().toISOString()
const seed = [
  ['angielski', null, 'main', 'Nauka języka angielskiego', 'Małe kroki każdego dnia.', '2026-08-30', 0],
  ['slowka', 'angielski', 'subtask', 'Słówka', 'Codziennie ucz się nowych słówek i utrwalaj wcześniejsze poznane.', '2026-08-20', 0],
  ['hello', 'slowka', 'detail', 'Hello', '', '', 0, true],
  ['how', 'slowka', 'detail', 'How are you?', '', '', 0],
  ['thanks', 'slowka', 'detail', 'Thank you', '', '', 0],
  ['gramatyka', 'angielski', 'subtask', 'Gramatyka', 'Present Simple', '2026-08-25', 1],
  ['praca', null, 'main', 'Projekt do pracy', 'Materiały i prezentacja', '2026-09-10', 1],
  ['trening', null, 'main', 'Trening', 'Plan treningowy', '', 2],
  ['dom', null, 'main', 'Domowe obowiązki', '', '', 3],
].map(([id,parentId,level,title,description,dueDate,color,completed=false])=>({id,parentId,level,title,description,dueDate,color,completed,archived:completed,completedAt:completed?now:null,deleted:false,images:[],createdAt:now}))
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`
const fmt=(d,time=false)=>d?new Intl.DateTimeFormat('pl-PL',time?{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d)):''
const compressImage=file=>new Promise((resolve,reject)=>{
 const url=URL.createObjectURL(file),img=new Image()
 img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.72))}
 img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Nie udało się odczytać zdjęcia.'))};img.src=url
})

export default function App(){
 const [tasks,setTasks]=useState(()=>{try{return JSON.parse(localStorage.getItem('planner-tasks'))||seed}catch{return seed}})
 const [view,setView]=useState({name:'home'}),[toast,setToast]=useState(''),[filter,setFilter]=useState('Wszystkie')
 const timer=useRef()
 useEffect(()=>{try{localStorage.setItem('planner-tasks',JSON.stringify(tasks))}catch{setToast('Brak miejsca na zdjęcia. Usuń jedno i spróbuj ponownie.')}},[tasks])
 const parent=id=>tasks.find(t=>t.id===id), children=id=>tasks.filter(t=>t.parentId===id&&!t.deleted), active=id=>children(id).filter(t=>!t.archived)
 const nav=v=>{setView(v);scrollTo(0,0)}
 const flash=m=>{setToast(m);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),2800)}
 const toggle=t=>{const done=!t.completed,n=new Date().toISOString();setTasks(a=>a.map(x=>x.id===t.id?{...x,completed:done,archived:done,completedAt:done?n:null,archivedAt:done?n:null}:x));flash(done?'Gotowe! Przeniesiono do archiwum.':'Zadanie przywrócono.')}
 const patch=(id,data)=>setTasks(a=>a.map(x=>x.id===id?{...x,...(typeof data==='function'?data(x):data),updatedAt:new Date().toISOString()}:x))
 const trash=(t,goHome=true)=>{const ids=new Set([t.id]);let change=true;while(change){change=false;tasks.forEach(x=>{if(ids.has(x.parentId)&&!ids.has(x.id)){ids.add(x.id);change=true}})};setTasks(a=>a.map(x=>ids.has(x.id)?{...x,deleted:true,deletedAt:new Date().toISOString()}:x));flash('Przeniesiono do kosza.');if(goHome)nav({name:'home'})}
 const save=d=>{const n=new Date().toISOString(),savedId=d.id||uid();if(d.id)setTasks(a=>a.map(x=>x.id===d.id?{...x,...d,updatedAt:n}:x));else setTasks(a=>[...a,{...d,id:savedId,createdAt:n,completed:false,archived:false,deleted:false,images:d.images||[],color:d.color??a.length%5}]);flash(d.id?'Zmiany zapisane.':d.level==='main'?'Projekt utworzony.':'Zadanie dodane.');if(d.parentId)nav({name:'task',id:d.parentId});else nav({name:'task',id:savedId})}
 const path=t=>{const names=[];let x=t;while(x?.parentId){x=parent(x.parentId);if(x)names.unshift(x.title)}return names.join(' › ')}
 const cur=parent(view.id)
 let page
 if(view.name==='form')page=<TaskForm task={cur} parentTask={parent(view.parentId)} onCancel={()=>view.parentId?nav({name:'task',id:view.parentId}):nav({name:'home'})} onSave={save} onTrash={trash}/>
 else if(view.name==='archive')page=<Archive tasks={tasks} filter={filter} setFilter={setFilter} path={path} onRestore={toggle} onTrash={trash}/>
 else if(view.name==='trash')page=<Trash tasks={tasks} setTasks={setTasks} flash={flash}/>
 else if(view.name==='task'&&cur)page=<TaskView task={cur} items={active(cur.id)} getChildren={children} onBack={()=>cur.parentId?nav({name:'task',id:cur.parentId}):nav({name:'home'})} onOpen={id=>nav({name:'task',id})} onAdd={()=>nav({name:'form',parentId:cur.id})} onPatch={data=>patch(cur.id,data)} onToggle={toggle} onTrash={t=>trash(t,false)}/>
 else page=<Home tasks={tasks.filter(t=>!t.parentId&&!t.archived&&!t.deleted)} getChildren={children} onOpen={id=>nav({name:'task',id})} onAdd={()=>nav({name:'form'})} onEdit={id=>nav({name:'form',id})} onTrash={t=>trash(t,false)}/>
 return <><main className="phone-app">{page}{toast&&<div className="toast"><span>✓</span>{toast}</div>}</main>{view.name!=='form'&&createPortal(<BottomNav active={view.name} go={nav}/>,document.body)}</>
}

function Header({title='Moje projekty',back,onBack,action}){return <header className="topbar">{back?<button className="icon-btn" onClick={onBack} aria-label="Wróć">‹</button>:<span/>}<strong>{title}</strong>{action?<button className="add-round" onClick={action} aria-label="Dodaj zadanie"/>:<span/>}</header>}
function Home({tasks,onOpen,onAdd}){return <><Header/><section className="content simple-home"><div className="home-heading"><h1>Projekty</h1><button className="secondary" onClick={onAdd}>+ Nowy projekt</button></div><div className="project-list">{tasks.map(t=><button className="project-card" key={t.id} onClick={()=>onOpen(t.id)}><span><strong>{t.title}</strong><span>{getFocus(t).step?.title || (getFocus(t).complete ? 'Plan wykonany ✓' : 'Ułóż zadania w Planie')}</span></span><span aria-hidden="true">›</span></button>)}</div>{!tasks.length&&<p className="muted-value">Zacznij od jednego projektu.</p>}</section></>}
function TaskRow({task,kids=[],color=0,onOpen,onEdit,onToggle,onTrash}){const done=kids.filter(x=>x.completed).length,[offset,setOffset]=useState(0),start=useRef(0),dragging=useRef(false);const touchStart=e=>{start.current=e.touches[0].clientX;dragging.current=false};const touchMove=e=>{const dx=e.touches[0].clientX-start.current;if(Math.abs(dx)>6)dragging.current=true;setOffset(Math.max(-84,Math.min(0,dx)))};const touchEnd=()=>setOffset(offset<-42?-84:0);return <div className="swipe-row"><button className="swipe-delete" onClick={()=>{setOffset(0);onTrash?.()}}>Usuń</button><article className="task-row" style={{transform:`translateX(${offset}px)`}} onTouchStart={touchStart} onTouchMove={touchMove} onTouchEnd={touchEnd} onClick={()=>{if(dragging.current){dragging.current=false;return}if(offset<0)setOffset(0);else onOpen?.()}}>{onToggle?<button className={`check ${task.completed?'checked':''}`} onClick={e=>{e.stopPropagation();onToggle()}}>{task.completed?'✓':''}</button>:<div className="task-symbol" style={{'--tone':COLORS[task.color??color%5]}}>{ICONS[task.color??color%5]}</div>}<div className="task-copy"><h3>{task.title}</h3>{task.level==='main'&&<p className="project-next">→ {task.nextAction || 'Wybierz następną czynność'}</p>}<p>{task.level==='main'? (task.milestones?.find(m=>!m.done)?.title || 'Ustal etapy swojej drogi') : task.dueDate?`Do ${fmt(task.dueDate)}`:kids.length?`${done} z ${kids.length} wykonane`:'Bez terminu'}</p>{kids.length>0&&<div className="progress"><i style={{width:`${done/kids.length*100}%`}}/></div>}</div><button className="more" onClick={e=>{e.stopPropagation();onEdit?.()}}>•••</button><span className="chev">›</span></article></div>}
function TaskView({task,items,getChildren,onBack,onOpen,onAdd,onPatch,onToggle,onTrash}){
 const level=task.level==='main'?'Zadanie':task.level==='subtask'?'Podzadanie':'Krok'
 if(task.level==='main')return <><Header title={task.title} back onBack={onBack}/><section className="content"><ProjectPlanner key={task.id} task={task} onPatch={onPatch} onComplete={()=>{onToggle(task);onBack()}}><details className="project-materials"><summary>Zadania i materiały</summary>{task.description&&<InlineSection label="Opis" value={task.description} multiline onSave={description=>onPatch({description})}/>}{task.dueDate&&<InlineSection label="Termin" value={task.dueDate} type="date" onSave={dueDate=>onPatch({dueDate})}/>}{task.notes&&<InlineSection label="Notatki" value={task.notes} multiline onSave={notes=>onPatch({notes})}/>}{task.links&&<InlineSection label="Linki" value={task.links} multiline onSave={links=>onPatch({links})}/>}{task.images?.length>0&&<PhotoSection images={task.images} onSave={images=>onPatch({images})}/>}<div className="task-list">{items.map(t=><TaskRow key={t.id} task={t} kids={getChildren(t.id)} onOpen={()=>onOpen(t.id)} onEdit={()=>onOpen(t.id)} onToggle={()=>onToggle(t)} onTrash={()=>onTrash(t)}/>)}</div><button className="text-button" onClick={onAdd}>+ Dodaj zadanie</button></details><button className="text-button delete-project" onClick={()=>{onTrash(task);onBack()}}>Przenieś projekt do kosza</button></ProjectPlanner></section></>

 return <><Header title={task.title} back onBack={onBack} action={task.level!=='detail'?onAdd:null}/><section className="content knowledge-page">
  <div className="knowledge-status"><button className={`status-toggle ${task.completed?'done':''}`} onClick={()=>onToggle(task)}>{task.completed?'✓':'○'}</button><span>{task.completed?'Wykonane':level}</span></div>
  <InlineSection className="knowledge-title" label="Nazwa" value={task.title} onSave={title=>onPatch({title})}/>
  {task.dueDate&&<InlineSection label="Termin" value={task.dueDate} type="date" display={fmt(task.dueDate)} onSave={dueDate=>onPatch({dueDate})}/>}
  {task.description&&<InlineSection label="Opis" value={task.description} multiline onSave={description=>onPatch({description})}/>}
  {task.images?.length>0&&<PhotoSection images={task.images} onSave={images=>onPatch({images})}/>}
  {task.notes&&<InlineSection label="Notatki" value={task.notes} multiline onSave={notes=>onPatch({notes})}/>}
  {task.level!=='detail'&&items.length>0&&<section className="knowledge-section"><div className="section-head"><h2>{task.level==='main'?'Zadania i materiały':'Checklista'}</h2><span>{items.length}</span></div><div className="task-list">{items.map(t=><TaskRow key={t.id} task={t} kids={getChildren(t.id)} onOpen={()=>onOpen(t.id)} onEdit={()=>onOpen(t.id)} onToggle={()=>onToggle(t)} onTrash={()=>onTrash(t)}/>)}</div></section>}
  {task.links&&<InlineSection label="Linki i materiały" value={task.links} multiline onSave={links=>onPatch({links})}/>}
  <section className="knowledge-meta"><span>Utworzono {fmt(task.createdAt,true)}</span>{task.updatedAt&&<span>Edytowano {fmt(task.updatedAt,true)}</span>}</section>
 </section></>
}

function InlineSection({label,value,onSave,multiline,type='text',empty='Brak danych',display,className=''}){const [edit,setEdit]=useState(false),[draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);const save=()=>{onSave(draft.trim?.()??draft);setEdit(false)};return <section className={`knowledge-section ${className}`}><div className="section-head"><h2>{label}</h2><button aria-label={`Edytuj: ${label}`} onClick={()=>setEdit(true)}>✎</button></div>{edit?<div className="inline-editor">{multiline?<textarea autoFocus rows="5" value={draft} onChange={e=>setDraft(e.target.value)}/>:<input autoFocus type={type} value={draft} onChange={e=>setDraft(e.target.value)}/>}<div><button onClick={()=>{setDraft(value);setEdit(false)}}>Anuluj</button><button className="inline-save" onClick={save}>Zapisz</button></div></div>:<p className={!value?'muted-value':''}>{display||value||empty}</p>}</section>}

function PhotoSection({images,onSave}){const [edit,setEdit]=useState(false),[open,setOpen]=useState(-1),ref=useRef(),track=useRef();useEffect(()=>{if(open>=0)requestAnimationFrame(()=>track.current?.scrollTo({left:open*track.current.clientWidth}))},[open]);const add=async e=>{try{const room=6-images.length,files=Array.from(e.target.files).slice(0,room),next=await Promise.all(files.map(compressImage));onSave([...images,...next]);setEdit(false)}catch(err){alert(err.message)}finally{e.target.value=''}};return <section className="knowledge-section"><div className="section-head"><h2>Zdjęcia</h2><button aria-label="Edytuj zdjęcia" onClick={()=>setEdit(!edit)}>✎</button></div>{images.length?<div className="knowledge-photos">{images.map((src,i)=><div key={i}><button className="photo-thumb" onClick={()=>setOpen(i)}><img src={src} alt={`Zdjęcie ${i+1}`}/></button>{edit&&<button className="remove-photo" onClick={()=>onSave(images.filter((_,n)=>n!==i))}>×</button>}</div>)}</div>:<p className="muted-value">Brak zdjęć</p>}{edit&&images.length<6&&<button className="add-inline-photo" onClick={()=>ref.current.click()}>Dodaj zdjęcie</button>}<input ref={ref} hidden type="file" accept="image/*" multiple onChange={add}/>{open>=0&&<div className="lightbox"><button className="lightbox-close" onClick={()=>setOpen(-1)}>×</button><div ref={track} className="lightbox-track" onScroll={e=>setOpen(Math.round(e.currentTarget.scrollLeft/e.currentTarget.clientWidth))}>{images.map((src,i)=><img key={i} src={src} alt=""/>)}</div><span>{open+1} / {images.length}</span></div>}</section>}
function TaskForm({task,parentTask,onSave,onCancel,onTrash}){const [d,setD]=useState(()=>task?{...task}:{parentId:parentTask?.id||null,level:parentTask?(parentTask.level==='main'?'subtask':'detail'):'main',title:'',description:'',dueDate:'',images:[]});const ref=useRef();const files=async e=>{try{const room=3-(d.images?.length||0),selected=Array.from(e.target.files).slice(0,room),images=await Promise.all(selected.map(compressImage));setD(x=>({...x,images:[...(x.images||[]),...images].slice(0,3)}))}catch(err){alert(err.message)}finally{e.target.value=''}};if(d.level==='main')return <><Header title={task?'Edytuj projekt':'Nowy projekt'} back onBack={onCancel}/><form className="content simple-plan new-project" onSubmit={e=>{e.preventDefault();if(d.title.trim())onSave({...d,title:d.title.trim()})}}><label htmlFor="project-name">Nazwa projektu</label><input id="project-name" autoFocus required maxLength="80" value={d.title} onChange={e=>setD({...d,title:e.target.value})} placeholder="Np. Angielski"/><button className="primary">{task?'Zapisz':'Utwórz projekt'}</button></form></>;return <><Header title={task?'Edytuj':parentTask?'Nowe zadanie':'Nowy projekt'} back onBack={onCancel}/><form className="content form" onSubmit={e=>{e.preventDefault();if(d.title.trim())onSave({...d,title:d.title.trim()})}}><div className="form-intro"><div><h1>{task?'Edytuj':parentTask?'Nowe zadanie':'Nowy projekt'}</h1>{parentTask&&<p>{parentTask.title}</p>}</div></div><label>Nazwa<input autoFocus required maxLength="80" value={d.title} onChange={e=>setD({...d,title:e.target.value})} placeholder="Nazwa zadania"/></label><label>Opis <em>opcjonalnie</em><textarea rows="4" value={d.description} onChange={e=>setD({...d,description:e.target.value})} placeholder="Opis"/></label><label>Termin <em>opcjonalnie</em><input type="date" value={d.dueDate} onChange={e=>setD({...d,dueDate:e.target.value})}/></label><label>Zdjęcia <em>do 3</em></label><div className="photo-grid">{d.images?.map((s,i)=><div className="photo" key={i}><img src={s}/><button type="button" onClick={()=>setD({...d,images:d.images.filter((_,n)=>n!==i)})}>×</button></div>)}{(d.images?.length||0)<3&&<button type="button" className="photo-add" onClick={()=>ref.current.click()}>▧<span>Dodaj</span></button>}</div><input ref={ref} hidden type="file" accept="image/*" multiple onChange={files}/><button className="primary save">Zapisz</button>{task&&<button type="button" className="danger" onClick={()=>confirm(`Przenieść „${task.title}” do kosza?`)&&onTrash(task)}>Przenieś do kosza</button>}</form></>}
function Archive({tasks,filter,setFilter,path,onRestore,onTrash}){const list=useMemo(()=>tasks.filter(t=>t.archived&&!t.deleted).filter(t=>filter==='Dzisiaj'?new Date(t.completedAt).toDateString()===new Date().toDateString():filter==='7 dni'?Date.now()-new Date(t.completedAt)<604800000:true).sort((a,b)=>new Date(b.completedAt)-new Date(a.completedAt)),[tasks,filter]);return <><Header title="Archiwum"/><section className="content"><Heading small="Twoje postępy" text="Wykonane zadania"/><div className="filters">{['Wszystkie','Dzisiaj','7 dni'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="archive-list">{list.map(t=><ArchiveRow key={t.id} task={t} subtitle={path(t)||'Zadanie główne'} onRestore={()=>onRestore(t)} onRemove={()=>onTrash(t)}/>)}</div>{!list.length&&<Empty text="Brak wykonanych zadań w tym okresie."/ >}</section></>}
function ArchiveRow({task,subtitle,onRestore,onRemove,trash}){return <article className="archive-row"><span className={trash?'trash-icon':''}>{trash?'♲':'✓'}</span><div><h3>{task.title}</h3>{subtitle&&<p>{subtitle}</p>}<small>{trash?'Usunięto':'Wykonano'} {fmt(trash?task.deletedAt:task.completedAt,true)}</small></div><button onClick={onRestore}>Przywróć</button><button className="mini-trash" onClick={onRemove}>{trash?'×':'♲'}</button></article>}
function Trash({tasks,setTasks,flash}){const list=tasks.filter(t=>t.deleted);return <><Header title="Kosz"/><section className="content"><Heading small="Bezpieczne usuwanie" text="Usunięte zadania"/><div className="archive-list">{list.map(t=><ArchiveRow trash key={t.id} task={t} onRestore={()=>{setTasks(a=>a.map(x=>x.id===t.id?{...x,deleted:false}:x));flash('Zadanie przywrócono.')}} onRemove={()=>confirm('Usunąć na zawsze?')&&setTasks(a=>a.filter(x=>x.id!==t.id))}/>)}</div>{!list.length&&<Empty text="Kosz jest pusty."/ >}</section></>}
function Heading({small,text}){return <div className="page-heading"><p>{small}</p><h1>{text}</h1></div>}function Empty({text,action}){return <div className="empty"><div>✓</div><h3>Wszystko uporządkowane</h3><p>{text}</p>{action&&<button onClick={action}>Dodaj zadanie</button>}</div>}
function NavIcon({name}){if(name==='home')return <svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8v10h-6v-6H9v6H3Z"/></svg>;if(name==='archive')return <svg viewBox="0 0 24 24"><path d="M4 7h16v14H4zM3 3h18v4H3zM9 11h6"/></svg>;return <svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6"/></svg>}
function BottomNav({active,go}){return <nav className="bottom-nav"><button aria-label="Projekty" className={['home','task'].includes(active)?'active':''} onClick={()=>go({name:'home'})}><NavIcon name="home"/><span>Projekty</span></button><button aria-label="Archiwum" className={active==='archive'?'active':''} onClick={()=>go({name:'archive'})}><NavIcon name="archive"/><span>Archiwum</span></button><button aria-label="Kosz" className={active==='trash'?'active':''} onClick={()=>go({name:'trash'})}><NavIcon name="trash"/><span>Kosz</span></button></nav>}
